const movieList = [
    "Inception",
    "The Matrix",
    "Titanic",
    "Avatar",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "The Shawshank Redemption",
    "Gladiator",
    "Fight Club",
    "Interstellar",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Jurassic Park",
    "Schindler's List",
    "The Silence of the Lambs",
    "The Departed",
    "The Lion King",
    "Saving Private Ryan",
    "Braveheart",
    "Goodfellas",
    "Die Hard",
    "The Wizard of Oz",
    "Spider-Man: No Way Home",
    "Black Panther",
    "Mad Max: Fury Road",
    "Wonder Woman",
    "The Social Network",
    "12 Angry Men",
    "Coco",
];

export default movieList;
